<div id="<?php print $params['prefix']; ?>mediapager" class="<?php print $params['prefix']; ?>ui-widget-header <?php print $params['prefix']; ?>ui-corner-bottom">    
  <div id="<?php print $params['prefix']; ?>mediapagerleft">
    <div id="<?php print $params['prefix']; ?>mediaprevpage" class="<?php print $params['prefix']; ?>mediapagerlink <?php print $params['prefix']; ?>ui-state-default <?php print $params['prefix']; ?>ui-corner-all"><span class="<?php print $params['prefix']; ?>ui-icon <?php print $params['prefix']; ?>ui-icon-seek-prev"></span></div>
    <div id="<?php print $params['prefix']; ?>medialoadprev" class="<?php print $params['prefix']; ?>mediapagerlink <?php print $params['prefix']; ?>ui-state-default <?php print $params['prefix']; ?>ui-corner-all"><span class="<?php print $params['prefix']; ?>ui-icon <?php print $params['prefix']; ?>ui-icon-triangle-1-w"></span></div>
    <div id="<?php print $params['prefix']; ?>mediaprev" class="<?php print $params['prefix']; ?>mediapagerlink <?php print $params['prefix']; ?>ui-state-default <?php print $params['prefix']; ?>ui-corner-all"><span class="<?php print $params['prefix']; ?>ui-icon <?php print $params['prefix']; ?>ui-icon-carat-1-w"></span></div>
  </div>
  <div id="<?php print $params['prefix']; ?>mediapagerright">
    <div id="<?php print $params['prefix']; ?>medianext" class="<?php print $params['prefix']; ?>mediapagerlink <?php print $params['prefix']; ?>ui-state-default <?php print $params['prefix']; ?>ui-corner-all"><span class="<?php print $params['prefix']; ?>ui-icon <?php print $params['prefix']; ?>ui-icon-carat-1-e"></span></div>
    <div id="<?php print $params['prefix']; ?>medialoadnext" class="<?php print $params['prefix']; ?>mediapagerlink <?php print $params['prefix']; ?>ui-state-default <?php print $params['prefix']; ?>ui-corner-all"><span class="<?php print $params['prefix']; ?>ui-icon <?php print $params['prefix']; ?>ui-icon-triangle-1-e"></span></div>
    <div id="<?php print $params['prefix']; ?>medianextpage" class="<?php print $params['prefix']; ?>mediapagerlink <?php print $params['prefix']; ?>ui-state-default <?php print $params['prefix']; ?>ui-corner-all"><span class="<?php print $params['prefix']; ?>ui-icon <?php print $params['prefix']; ?>ui-icon-seek-next"></span></div>
  </div>
</div>