var osmplayer=osmplayer||{};osmplayer.playLoader=osmplayer.playLoader||{};osmplayer.playLoader["default"]=function(a,b){minplayer.playLoader.call(this,a,b)};osmplayer.playLoader["default"].prototype=new minplayer.playLoader;osmplayer.playLoader["default"].prototype.constructor=osmplayer.playLoader["default"];
osmplayer.playLoader["default"].prototype.getDisplay=function(){this.options.build&&jQuery(".minplayer-default",this.context).prepend('    <div class="minplayer-default-loader-wrapper">      <div class="minplayer-default-big-play ui-state-default"><span></span></div>      <div class="minplayer-default-loader">&nbsp;</div>      <div class="minplayer-default-preview ui-widget-content"></div>    </div>');return jQuery(".minplayer-default .minplayer-default-loader-wrapper",this.context)};
osmplayer.playLoader["default"].prototype.getElements=function(){var a=minplayer.playLoader.prototype.getElements.call(this);return jQuery.extend(a,{busy:jQuery(".minplayer-default-loader",this.display),bigPlay:jQuery(".minplayer-default-big-play",this.display),preview:jQuery(".minplayer-default-preview",this.display)})};osmplayer=osmplayer||{};osmplayer.controller=osmplayer.controller||{};osmplayer.controller["default"]=function(a,b){minplayer.controller.call(this,a,b)};
osmplayer.controller["default"].prototype=new minplayer.controller;osmplayer.controller["default"].prototype.constructor=osmplayer.controller["default"];osmplayer.controller["default"].prototype.construct=function(){minplayer.controller.prototype.construct.call(this);this.get("player",function(a){minplayer.showThenHide(this.display,5E3,function(b){a.display[b?"addClass":"removeClass"]("with-controller")})})};
osmplayer.controller["default"].prototype.getDisplay=function(){this.options.build&&jQuery(".minplayer-default",this.context).prepend('    <div class="minplayer-default-controls ui-widget-header">      <div class="minplayer-default-controls-left">        <a class="minplayer-default-play minplayer-default-button ui-state-default ui-corner-all" title="Play">          <span class="ui-icon ui-icon-play"></span>        </a>        <a class="minplayer-default-pause minplayer-default-button ui-state-default ui-corner-all" title="Pause">          <span class="ui-icon ui-icon-pause"></span>        </a>      </div>      <div class="minplayer-default-controls-right">        <div class="minplayer-default-timer">00:00</div>        <div class="minplayer-default-fullscreen ui-widget-content">          <div class="minplayer-default-fullscreen-inner ui-state-default"></div>        </div>        <div class="minplayer-default-volume">          <div class="minplayer-default-volume-slider"></div>          <a class="minplayer-default-volume-mute minplayer-default-button ui-state-default ui-corner-all" title="Mute">            <span class="ui-icon ui-icon-volume-on"></span>          </a>          <a class="minplayer-default-volume-unmute minplayer-default-button ui-state-default ui-corner-all" title="Unmute">            <span class="ui-icon ui-icon-volume-off"></span>          </a>        </div>      </div>      <div class="minplayer-default-controls-mid">        <div class="minplayer-default-seek">          <div class="minplayer-default-progress ui-state-default"></div>        </div>      </div>    </div>');
this.context.addClass("with-controller");return jQuery(".minplayer-default-controls",this.context)};
osmplayer.controller["default"].prototype.getElements=function(){var a=minplayer.controller.prototype.getElements.call(this),b=jQuery(".minplayer-default-timer",this.display);return jQuery.extend(a,{play:jQuery(".minplayer-default-play",this.display),pause:jQuery(".minplayer-default-pause",this.display),fullscreen:jQuery(".minplayer-default-fullscreen",this.display),seek:jQuery(".minplayer-default-seek",this.display),progress:jQuery(".minplayer-default-progress",this.display),volume:jQuery(".minplayer-default-volume-slider",
this.display),mute:jQuery(".minplayer-default-volume-mute",this.display),timer:b,duration:b})};osmplayer=osmplayer||{};osmplayer.playlist=osmplayer.playlist||{};osmplayer.playlist["default"]=function(a,b){osmplayer.playlist.call(this,a,b)};osmplayer.playlist["default"].prototype=new osmplayer.playlist;osmplayer.playlist["default"].prototype.constructor=osmplayer.playlist["default"];
osmplayer.playlist["default"].prototype.construct=function(){this.options=jQuery.extend({showPlaylist:!0},this.options);osmplayer.playlist.prototype.construct.call(this);minplayer.showThenHide(this.elements.hideShow);this.get("player",function(a){var b=this.options.vertical?"width":"height",c=this.options.vertical?"right":"bottom",e=this.options.vertical?"marginRight":"marginBottom";this.hideShow=function(g,h){var f={},d={},i=this.display[b]();f[c]=g?i:0;h?a.elements.minplayer.animate(f,"fast"):a.elements.minplayer.css(f);
d[e]=g?0:-i;h?this.display.animate(d,"fast",function(){a.resize()}):this.display.css(d)};this.elements.hideShow&&this.elements.hideShow.bind("click",function(a){return function(b){b.preventDefault();var c=jQuery("span",a.elements.hideShow),b=a.options.vertical?"e":"s",d=a.options.vertical?"w":"n",c=c.hasClass("ui-icon-triangle-1-"+d);jQuery("span",a.elements.hideShow).removeClass(c?"ui-icon-triangle-1-"+d:"ui-icon-triangle-1-"+b).addClass(c?"ui-icon-triangle-1-"+b:"ui-icon-triangle-1-"+d);a.hideShow(c,
!0)}}(this));a.elements.minplayer&&(this.options.showPlaylist?this.options.vertical?a.elements.minplayer.css("right",this.display.width()+"px"):a.elements.minplayer.css("bottom",this.display.height()+"px"):this.hideShow(!1))})};
osmplayer.playlist["default"].prototype.getDisplay=function(){this.options.build&&this.context.append('    <div class="osmplayer-default-playlist">      <div class="osmplayer-default-hide-show-playlist ui-state-default">        <span class="ui-icon"></span>      </div>    </div>');return jQuery(".osmplayer-default-playlist",this.context)};
osmplayer.playlist["default"].prototype.getElements=function(){var a=osmplayer.playlist.prototype.getElements.call(this),b=this.options.vertical?"playlist-vertical":"playlist-horizontal",b=b+(this.options.playlistOnly?" playlist-only":""),c=this.options.showPlaylist,c=this.options.vertical?c?"e":"w":c?"s":"n",e=this.options.vertical?"ui-corner-left":"ui-corner-top";this.display.addClass(b);b=jQuery(".osmplayer-default-hide-show-playlist",this.display);b.addClass(e);this.options.playlistOnly&&(b.hide(),
b=null);jQuery("span",b).addClass("ui-icon-triangle-1-"+c);return jQuery.extend(a,{hideShow:b})};osmplayer=osmplayer||{};osmplayer.teaser=osmplayer.teaser||{};osmplayer.teaser["default"]=function(a,b){osmplayer.teaser.call(this,a,b)};osmplayer.teaser["default"].prototype=new osmplayer.teaser;osmplayer.teaser["default"].prototype.constructor=osmplayer.teaser["default"];
osmplayer.teaser["default"].prototype.construct=function(){minplayer.display.prototype.construct.call(this);this.display.bind("mouseenter",function(a){return function(){a.addClass("ui-state-hover")}}(this.elements.info)).bind("mouseleave",function(a){return function(){a.removeClass("ui-state-hover")}}(this.elements.info))};
osmplayer.teaser["default"].prototype.getDisplay=function(){this.context.append('  <div class="osmplayer-default-teaser ui-widget-content">    <div class="osmplayer-default-teaser-image"></div>    <div class="osmplayer-default-teaser-info ui-state-default">      <div class="osmplayer-default-teaser-title">Sample Title</div>    </div>  </div>');var a=jQuery(".osmplayer-default-teaser",this.context);return a.eq(a.length-1)};
osmplayer.teaser["default"].prototype.select=function(a){a?this.elements.info.addClass("ui-state-active"):this.elements.info.removeClass("ui-state-active")};osmplayer.teaser["default"].prototype.getElements=function(){var a=osmplayer.teaser.prototype.getElements.call(this);return jQuery.extend(a,{info:jQuery(".osmplayer-default-teaser-info",this.display),title:jQuery(".osmplayer-default-teaser-title",this.display),image:jQuery(".osmplayer-default-teaser-image",this.display)})};
osmplayer=osmplayer||{};osmplayer.scroll=osmplayer.scroll||{};osmplayer.scroll["default"]=function(a,b){osmplayer.scroll.call(this,a,b)};osmplayer.scroll["default"].prototype=new osmplayer.scroll;osmplayer.scroll["default"].prototype.constructor=osmplayer.scroll["default"];
osmplayer.scroll["default"].prototype.getDisplay=function(){this.options.build&&this.context.append('    <div class="osmplayer-default-playlist-scroll ui-widget-content">      <div class="osmplayer-default-playlist-scrollbar"></div>      <div class="minplayer-default-loader-wrapper">        <div class="minplayer-default-loader"></div>      </div>      <div class="osmplayer-default-playlist-list"></div>    </div>');return jQuery(".osmplayer-default-playlist-scroll",this.context)};
osmplayer.scroll["default"].prototype.getElements=function(){var a=osmplayer.scroll.prototype.getElements.call(this);return jQuery.extend(a,{playlist_busy:jQuery(".minplayer-default-loader-wrapper",this.display),list:jQuery(".osmplayer-default-playlist-list",this.display),scroll:jQuery(".osmplayer-default-playlist-scrollbar",this.display)})};osmplayer=osmplayer||{};osmplayer.pager=osmplayer.pager||{};osmplayer.pager["default"]=function(a,b){osmplayer.pager.call(this,a,b)};
osmplayer.pager["default"].prototype=new osmplayer.pager;osmplayer.pager["default"].prototype.constructor=osmplayer.pager["default"];
osmplayer.pager["default"].prototype.getDisplay=function(){this.options.build&&this.context.append('    <div class="osmplayer-default-playlist-pager ui-widget-header">      <div class="osmplayer-default-playlist-pager-left">        <a href="#" class="osmplayer-default-playlist-pager-link osmplayer-default-playlist-pager-prevpage minplayer-default-button ui-state-default ui-corner-all">          <span class="ui-icon ui-icon-circle-triangle-w"></span>        </a>      </div>      <div class="osmplayer-default-playlist-pager-right">        <a href="#" class="osmplayer-default-playlist-pager-link osmplayer-default-playlist-pager-nextpage minplayer-default-button ui-state-default ui-corner-all">          <span class="ui-icon ui-icon-circle-triangle-e"></span>        </a>      </div>    </div>');return jQuery(".osmplayer-default-playlist-pager",
this.context)};osmplayer.pager["default"].prototype.getElements=function(){var a=osmplayer.pager.prototype.getElements.call(this);return jQuery.extend(a,{prevPage:jQuery(".osmplayer-default-playlist-pager-prevpage",this.display),nextPage:jQuery(".osmplayer-default-playlist-pager-nextpage",this.display)})};osmplayer=osmplayer||{};osmplayer["default"]=function(a,b){osmplayer.call(this,a,b)};osmplayer["default"].prototype=new osmplayer;osmplayer["default"].prototype.constructor=osmplayer["default"];
osmplayer["default"].prototype.getDisplay=function(){0==this.context.children().length&&(this.context=this.context.attr({id:this.options.id+"-player","class":"minplayer-default-media"}).wrap(jQuery(document.createElement("div")).attr({"class":"minplayer-default-display ui-widget-content"})).parent(".minplayer-default-display").wrap(jQuery(document.createElement("div")).attr({"class":"minplayer-default"})).parent(".minplayer-default").prepend('      <div class="minplayer-default-logo"></div>      <div class="minplayer-default-error"></div>').wrap(jQuery(document.createElement("div")).attr({id:this.options.id,
"class":"osmplayer-default player-ui"})).parent(".osmplayer-default"),this.options.build=!0);return this.context};
osmplayer["default"].prototype.getElements=function(){var a=osmplayer.prototype.getElements.call(this);this.display.width(this.options.width);this.display.height(this.options.height);var b=jQuery(".minplayer-default",this.display);this.options.playlistOnly&&(b.remove(),b=null);var c=jQuery(".osmplayer-default-playlist",this.display);this.options.disablePlaylist&&(c.remove(),c=null);return jQuery.extend(a,{player:this.display,minplayer:b,display:jQuery(".minplayer-default-display",this.display),media:jQuery(".minplayer-default-media",
this.display),error:jQuery(".minplayer-default-error",this.display),logo:jQuery(".minplayer-default-logo",this.display),playlist:c})};osmplayer.controller=osmplayer.controller||{};osmplayer.controller["default"]=function(a,b){minplayer.controller.call(this,a,b)};osmplayer.controller["default"].prototype=new minplayer.controller;osmplayer.controller["default"].prototype.constructor=osmplayer.controller["default"];
osmplayer.controller["default"].prototype.construct=function(){minplayer.controller.prototype.construct.call(this);this.get("player",function(a){minplayer.showThenHide(this.display,5E3,function(b){a.display[b?"addClass":"removeClass"]("with-controller")})})};
osmplayer.controller["default"].prototype.getDisplay=function(){this.options.build&&jQuery(".minplayer-default",this.context).prepend('    <div class="minplayer-default-controls ui-widget-header">      <div class="minplayer-default-controls-left">        <a class="minplayer-default-play minplayer-default-button ui-state-default ui-corner-all" title="Play">          <span class="ui-icon ui-icon-play"></span>        </a>        <a class="minplayer-default-pause minplayer-default-button ui-state-default ui-corner-all" title="Pause">          <span class="ui-icon ui-icon-pause"></span>        </a>      </div>      <div class="minplayer-default-controls-right">        <div class="minplayer-default-timer">00:00</div>        <div class="minplayer-default-fullscreen ui-widget-content">          <div class="minplayer-default-fullscreen-inner ui-state-default"></div>        </div>        <div class="minplayer-default-volume">          <div class="minplayer-default-volume-slider"></div>          <a class="minplayer-default-volume-mute minplayer-default-button ui-state-default ui-corner-all" title="Mute">            <span class="ui-icon ui-icon-volume-on"></span>          </a>          <a class="minplayer-default-volume-unmute minplayer-default-button ui-state-default ui-corner-all" title="Unmute">            <span class="ui-icon ui-icon-volume-off"></span>          </a>        </div>      </div>      <div class="minplayer-default-controls-mid">        <div class="minplayer-default-seek">          <div class="minplayer-default-progress ui-state-default"></div>        </div>      </div>    </div>');this.context.addClass("with-controller");
return jQuery(".minplayer-default-controls",this.context)};
osmplayer.controller["default"].prototype.getElements=function(){var a=minplayer.controller.prototype.getElements.call(this),b=jQuery(".minplayer-default-timer",this.display);return jQuery.extend(a,{play:jQuery(".minplayer-default-play",this.display),pause:jQuery(".minplayer-default-pause",this.display),fullscreen:jQuery(".minplayer-default-fullscreen",this.display),seek:jQuery(".minplayer-default-seek",this.display),progress:jQuery(".minplayer-default-progress",this.display),volume:jQuery(".minplayer-default-volume-slider",
this.display),mute:jQuery(".minplayer-default-volume-mute",this.display),timer:b,duration:b})};
